//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	operatorv1 "open-cluster-management.io/api/operator/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlplaneStorageOption) DeepCopyInto(out *ControlplaneStorageOption) {
	*out = *in
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalEtcdConfiguration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlplaneStorageOption.
func (in *ControlplaneStorageOption) DeepCopy() *ControlplaneStorageOption {
	if in == nil {
		return nil
	}
	out := new(ControlplaneStorageOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalEtcdConfiguration) DeepCopyInto(out *ExternalEtcdConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalEtcdConfiguration.
func (in *ExternalEtcdConfiguration) DeepCopy() *ExternalEtcdConfiguration {
	if in == nil {
		return nil
	}
	out := new(ExternalEtcdConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MulticlusterControlplane) DeepCopyInto(out *MulticlusterControlplane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MulticlusterControlplane.
func (in *MulticlusterControlplane) DeepCopy() *MulticlusterControlplane {
	if in == nil {
		return nil
	}
	out := new(MulticlusterControlplane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MulticlusterControlplane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MulticlusterControlplaneList) DeepCopyInto(out *MulticlusterControlplaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MulticlusterControlplane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MulticlusterControlplaneList.
func (in *MulticlusterControlplaneList) DeepCopy() *MulticlusterControlplaneList {
	if in == nil {
		return nil
	}
	out := new(MulticlusterControlplaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MulticlusterControlplaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MulticlusterControlplaneSpec) DeepCopyInto(out *MulticlusterControlplaneSpec) {
	*out = *in
	in.StorageOption.DeepCopyInto(&out.StorageOption)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MulticlusterControlplaneSpec.
func (in *MulticlusterControlplaneSpec) DeepCopy() *MulticlusterControlplaneSpec {
	if in == nil {
		return nil
	}
	out := new(MulticlusterControlplaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MulticlusterControlplaneStatus) DeepCopyInto(out *MulticlusterControlplaneStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Generations != nil {
		in, out := &in.Generations, &out.Generations
		*out = make([]operatorv1.GenerationStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MulticlusterControlplaneStatus.
func (in *MulticlusterControlplaneStatus) DeepCopy() *MulticlusterControlplaneStatus {
	if in == nil {
		return nil
	}
	out := new(MulticlusterControlplaneStatus)
	in.DeepCopyInto(out)
	return out
}
