# permissions for end users to edit multiclustercontrolplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: multiclustercontrolplane-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: multiclustercontrolplane-editor-role
rules:
- apiGroups:
  - operator.open-cluster-management.io
  resources:
  - multiclustercontrolplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.open-cluster-management.io
  resources:
  - multiclustercontrolplanes/status
  verbs:
  - get
